Add test for full sphere filtering of velocity

diff --git a/tests/Kemorin/Models/full_sphere_v_filter_static/Makefile b/tests/Kemorin/Models/full_sphere_v_filter_static/Makefile
--- a/tests/Kemorin/Models/full_sphere_v_filter_static/Makefile
+++ b/tests/Kemorin/Models/full_sphere_v_filter_static/Makefile
@@ -38,12 +38,35 @@ test:
 	
 	$(TARGET_SPH_PICK_MODE_CHECK)  reference/picked_mode_l1_m0c  monitor/picked_mode_l1_m0c >> log.txt
 	@if [ `tail -n 1 flag.txt` != 0 ]; then\
-		echo 'Failed Y_{0}^{0} data check'; \
+		echo 'Failed Y_{1}^{0} data check'; \
 		exit 1;\
 	fi
 	
-	$(TARGET_COMPARE_PSF)
-	@echo 'Spin up in full sphere check finished'
+	$(TARGET_SPH_PICK_MODE_CHECK)  reference/picked_mode_l6_m4c  monitor/picked_mode_l6_m4c >> log.txt
+	@if [ `tail -n 1 flag.txt` != 0 ]; then\
+		echo 'Failed Y_{6}^{4c} data check'; \
+		exit 1;\
+	fi
+	
+	$(TARGET_SPH_PICK_MODE_CHECK)  reference/picked_mode_l12_m12c  monitor/picked_mode_l12_m12c >> log.txt
+	@if [ `tail -n 1 flag.txt` != 0 ]; then\
+		echo 'Failed Y_{12}^{12c} data check'; \
+		exit 1;\
+	fi
+	
+	$(TARGET_SPH_PICK_MODE_CHECK)  reference/picked_mode_l16_m12c  monitor/picked_mode_l16_m12c >> log.txt
+	@if [ `tail -n 1 flag.txt` != 0 ]; then\
+		echo 'Failed Y_{16}^{12c} data check'; \
+		exit 1;\
+	fi
+	
+	$(TARGET_SPH_PICK_MODE_CHECK)  reference/picked_mode_l24_m14s  monitor/picked_mode_l24_m14s >> log.txt
+	@if [ `tail -n 1 flag.txt` != 0 ]; then\
+		echo 'Failed Y_{24}^{14s} data check'; \
+		exit 1;\
+	fi
+	
+	@echo 'Velocity filtering check in full sphere by static model is finished'
 
 clean:
 	rm -f *.dat *.txt rst_6/rst.* monitor/*.dat monitor/*.dat.gz sections/*.gz field/out.*
