Update source term tests using restart file

diff --git a/tests/Calypso/Models/static_heat_source_by_rst/Makefile b/tests/Calypso/Models/static_heat_source_by_rst/Makefile
--- a/tests/Calypso/Models/static_heat_source_by_rst/Makefile
+++ b/tests/Calypso/Models/static_heat_source_by_rst/Makefile
@@ -12,9 +12,7 @@ TARGET_SPH_INITIAL = sph_initial_field
 #
 MPIRUN = mpirun
 TARGET_SPH_MHD =             $(BUILDDIR)/sph_mhd
-TARGET_SPH_ENE_CHECK =       $(BUILDDIR)/tests/sph_ene_check
 TARGET_SPH_PICK_MODE_CHECK = $(BUILDDIR)/tests/sph_picked_mode_check
-TARGET_COMPARE_PSF =         $(SRCDIR)/bin/tests/compare_psf
 #
 
 all: test
@@ -27,10 +25,19 @@ test:
 	make $(TARGET_SPH_INITIAL)
 	$(MPIRUN) -np 1 $(TARGET_SPH_INITIAL)
 	$(MPIRUN) -np 1 $(TARGET_SPH_MHD)
+	
+	@sync
+	$(TARGET_SPH_PICK_MODE_CHECK)  reference/picked_mode_l0_m0c  picked_mode_l0_m0c >> log.txt
+	@if [ `tail -n 1 flag.txt` != 0 ]; then\
+		echo 'Failed Y_{0}^{0} data check'; \
+		exit 1;\
+	fi
+	@echo 'Static scalar fields with source check is finished'
 
 
 clean:
-	rm -f *~ sph_ave_volume_s.dat radial_point.dat time_total.dat
+	rm -f *~ *.txt sph_ave_volume_s.dat picked_mode_l0_m0c.dat
+	rm -f radial_point.dat time_total.dat
 	rm -f rst_1/rst.*
 	rm -fr $(TARGET_SPH_INITIAL) $(TARGET_SPH_INITIAL).dSYM
 
