Add new FFT tests with selector

diff --git a/tests/Calypso/FFT_test/Makefile b/tests/Calypso/FFT_test/Makefile
--- a/tests/Calypso/FFT_test/Makefile
+++ b/tests/Calypso/FFT_test/Makefile
@@ -9,6 +9,12 @@ SHELL           = /bin/sh
 SRCDIR = /Users/matsui/src_kemo
 BUILDDIR= $(SRCDIR)/bin
 #
+TARGET_SELECT_PRT_FFT_TEST = $(BUILDDIR)/tests/test_prt_select_FFT
+TARGET_SELECT_RTP_FFT_TEST = $(BUILDDIR)/tests/test_rtp_select_FFT
+#
+TARGET_FFTPACK_TEST =  $(BUILDDIR)/tests/test_FFTPACK
+TARGET_FFTPACK_TEST =  $(BUILDDIR)/tests/test_FFTPACK
+#
 TARGET_FFTPACK_TEST =  $(BUILDDIR)/tests/test_FFTPACK
 TARGET_ISPACK1_TEST =  $(BUILDDIR)/tests/test_ISPACK1
 TARGET_ISPACK3_TEST =  $(BUILDDIR)/tests/test_ISPACK3
@@ -96,6 +102,80 @@ test:
 		echo 'Failed OpenMP FFTW3 check'; \
 		exit 1;\
 	fi
+	
+	
+	$(TARGET_SELECT_RTP_FFT_TEST) control_OpenMP_FFTW
+	$(TARGET_CMPR_FFT_TEST) 'rtp_fftpack_test.dat' 'OMP_FFTW_test.dat' > log.txt
+	@if [ `tail -n 1 log.txt` != 0 ]; then\
+		echo 'Failed OpenMP FFTW3 check'; \
+		exit 1;\
+	fi
+	rm OMP_FFTW_test.dat
+	
+	$(TARGET_SELECT_RTP_FFT_TEST) control_FFTW
+	$(TARGET_CMPR_FFT_TEST) 'rtp_fftpack_test.dat' 'FFTW_test.dat' > log.txt
+	@if [ `tail -n 1 log.txt` != 0 ]; then\
+		echo 'Failed FFTW3 check'; \
+		exit 1;\
+	fi
+	rm FFTW_test.dat
+	
+	$(TARGET_SELECT_RTP_FFT_TEST) control_ISPACK3
+	$(TARGET_CMPR_FFT_TEST) 'rtp_fftpack_test.dat' 'ISPACK3_test.dat' > log.txt
+	@if [ `tail -n 1 log.txt` != 0 ]; then\
+		echo 'Failed ISPACK3 check'; \
+		exit 1;\
+	fi
+	rm ISPACK3_test.dat
+	
+	$(TARGET_SELECT_RTP_FFT_TEST) control_ISPACK1
+	$(TARGET_CMPR_FFT_TEST) 'rtp_fftpack_test.dat' 'ISPACK1_test.dat' > log.txt
+	@if [ `tail -n 1 log.txt` != 0 ]; then\
+		echo 'Failed ISPACK1 check'; \
+		exit 1;\
+	fi
+	rm ISPACK1_test.dat
+	
+	$(TARGET_SELECT_RTP_FFT_TEST) control_FFTPACK
+	$(TARGET_CMPR_FFT_TEST) 'rtp_fftpack_test.dat' 'FFTPACK_test.dat' > log.txt
+	@if [ `tail -n 1 log.txt` != 0 ]; then\
+		echo 'Failed FFTPACK check'; \
+		exit 1;\
+	fi
+	rm FFTPACK_test.dat
+	
+	
+	$(TARGET_SELECT_PRT_FFT_TEST) control_FFTW
+	$(TARGET_CMPR_FFT_TEST) 'rtp_fftpack_test.dat' 'FFTW_test.dat' > log.txt
+	@if [ `tail -n 1 log.txt` != 0 ]; then\
+		echo 'Failed Phi inside FFTW3 check'; \
+		exit 1;\
+	fi
+	rm FFTW_test.dat
+	
+	$(TARGET_SELECT_PRT_FFT_TEST) control_ISPACK3
+	$(TARGET_CMPR_FFT_TEST) 'rtp_fftpack_test.dat' 'ISPACK3_test.dat' > log.txt
+	@if [ `tail -n 1 log.txt` != 0 ]; then\
+		echo 'Failed Phi inside ISPACK3 check'; \
+		exit 1;\
+	fi
+	rm ISPACK3_test.dat
+	
+	$(TARGET_SELECT_PRT_FFT_TEST) control_ISPACK1
+	$(TARGET_CMPR_FFT_TEST) 'rtp_fftpack_test.dat' 'ISPACK1_test.dat' > log.txt
+	@if [ `tail -n 1 log.txt` != 0 ]; then\
+		echo 'Failed Phi inside ISPACK1 check'; \
+		exit 1;\
+	fi
+	rm ISPACK1_test.dat
+	
+	$(TARGET_SELECT_PRT_FFT_TEST) control_FFTPACK
+	$(TARGET_CMPR_FFT_TEST) 'rtp_fftpack_test.dat' 'FFTPACK_test.dat' > log.txt
+	@if [ `tail -n 1 log.txt` != 0 ]; then\
+		echo 'Failed Phi inside FFTPACK check'; \
+		exit 1;\
+	fi
+	rm FFTPACK_test.dat
 	
 	echo 'FFT check finished'
 
