Add latent heat model test in tests

diff --git a/tests/Kemorin/Models/static_latent_heat_by_ctl/Makefile b/tests/Kemorin/Models/static_latent_heat_by_ctl/Makefile
--- a/tests/Kemorin/Models/static_latent_heat_by_ctl/Makefile
+++ b/tests/Kemorin/Models/static_latent_heat_by_ctl/Makefile
@@ -8,6 +8,7 @@ BUILDDIR = $(SRCDIR)/bin
 MPIRUN = mpirun
 TARGET_SPH_MHD =             $(BUILDDIR)/sph_mhd
 TARGET_SPH_PICK_MODE_CHECK = $(BUILDDIR)/tests/sph_picked_mode_check
+TARGET_SPH_REF_CHECK =       $(BUILDDIR)/tests/sph_ref_field_check
 #
 
 all: test
@@ -20,6 +21,11 @@ test:
 	$(TARGET_SPH_PICK_MODE_CHECK)  reference/picked_mode_l0_m0c  picked_mode_l0_m0c >> log.txt
 	@if [ `tail -n 1 flag.txt` != 0 ]; then\
 		echo 'Failed Y_{0}^{0} data check'; \
+		exit 1;\
+	fi
+	$(TARGET_SPH_REF_CHECK)  reference/reference_fields.dat     reference_fields.dat >> log.txt
+	@if [ `tail -n 1 flag.txt` != 0 ]; then\
+		echo 'Failed refernce field data (reference_fields.dat) check'; \
 		exit 1;\
 	fi
 	@echo 'Static scalar fields with inner core is finished'
